# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Larry Hsiao"
email: larryhsiao@silverhetch.com
description: > # this means to ignore newlines until "baseurl:"
    An Android Developer.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://silverhetch.com" # the base hostname & protocol for your site
github_username:  LarryHsiao

# Build settings
markdown: kramdown

theme: tale
permalink: /:year-:month-:day/:title
paginate: 5
