base_url = "https://larryhsiao.com"

title = "LH Blog"
description=""

highlight_theme = "solarized-light"
generate_rss = true
rss_limit = 20

compile_sass = true

highlight_code = true

build_search_index = true

theme = "Ergo"

[extra]
profile = "profile.svg" # the name of the profile picture in static/img/
website = "larryhsiao.com"
github = "LarryHsiao"
#twitter = "insipx"
# linkedin = ""
email = "larryhsiao@larryhsiao.com"
# instagram = ""
# keybase = ""
# reddit = ""
# youtube = ""

