# The URL the site will be built for
base_url = "https://larryhsiao.com"

# Used in feeds
title = "賴瑞Blog"
description = ""

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
# To enable this, build zola with chinese index enable.
build_search_index = false 
default_language = "zh"

minify_html = true

gnerate_feed = true
feed_filename = "feed.xml"
feed_limit = 5

taxonomies = [
    {name = "tags", rss = true},
]

[languages.en]
build_search_index = true
title = "LH Blog"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "subway-madrid"
render_emoji = true

[search]
include_title = true
include_description = false
include_content = true

[extra]
menus = [
    { url = "$BASE_URL/about/", name = "關於我" },
    { url = "$BASE_URL/tags/", name = "標籤" },
    { url = "$BASE_URL/en/", name = "English" },
]

menus_en = [
    { url = "$BASE_URL/about/en", name = "About" },
    { url = "$BASE_URL/tags/", name = "Tags" },
    { url = "$BASE_URL/", name = "中文" },
]

